### ISSUE TITLE
.mat file is not being generated

### ISSUE THREAD

**Issue by juansc** [kdahlquist/GRNmap#133]
This issue was mentioned in #74.

When estimateparms = 0 there is no .mat file output and MATLAB shows the error: Error in output (line 140) outputDiag{3,2} = GRNstruct.GRNOutput.reg_out; Error in GRNmodel (line 34) GRNstruct = output(GRNstruct);

**Comment by juansc** [comment]
The file that was initially tested is 22-genes_47-edges_Dahlquist-data_Sigmoidal_forward_graph.xlsx. We need to create a minimal version of this file which creates the same problem.

**Comment by juansc** [comment]
We will test with the problem file.

**Comment by juansc** [comment]
We tested it and we don't see the error any more. Please review.

**Comment by kdahlquist** [comment]
I downloaded the released code for v1.4.2 and tried the file "22-genes_47-edges_Dahlquist-data_Sigmoidal_forward_graph.xlsx" packaged with this release to review this issue.

However, the file actually had the optimization parameter "estimate_params" = 1, so it was not actually doing a forward simulation as the filename suggests.  So it was not testing what this bug was supposed to be about.  Is this the reason that this bug is no longer seen?

Also, according to the filename "graph", it should be making the graphs, right?  However, the "make_graphs" parameter is set to 0.

Also the optimization_parameters sheet still had the extra "value" in the top row and the "Sheet" parameter as well.  The network, network_weights, and threshold_b sheets are also not in compliance with our latest naming conventions.

I know that this one has been review requested for a while, but I can't really close this when there seems to be problems.  Please comment.

**Comment by juansc** [comment]
I fixed the file to comply with the new naming conventions. I ran GRNmap after correcting the parameters and did not see any error.

**Comment by kdahlquist** [comment]
I downloaded the beta code today and tried the file "22-genes_47-edges_Dahlquist-data_Sigmoidal_forward_graph.xlsx" packaged with this release to review this issue.

This file is still not in compliance with our new naming conventions.  The optimization_parameters sheet still has a row for "Sheet", which should be removed.  Unless this is an actual feature of the test, we need to make sure that all of our files are in compliance with the new naming convention.

**Comment by kdahlquist** [comment]
I also deleted the row containing "Sheet" from the optimization_parameters worksheet from this file:
22-genes_47-edges_Dahlquist-data_Sigmoidal_forward_graph.xlsx

and tried to run it, but got an error.

Reference to non-existent field 'copy_counter'.

Error in output (line 167)
if GRNstruct.copy_counter >= GRNstruct.alpha_list_length

Error in GRNmodel (line 37)
    GRNstruct = output(GRNstruct);

I'm attaching the error log file that was generated.

No .mat file was generated.
[error_log.txt](https://github.com/kdahlquist/GRNmap/files/137059/error_log.txt)

**Comment by juansc** [comment]
This has been fixed.

**Comment by kdahlquist** [comment]
Verfied this is fixed with v1.4.4 release (running from code) and the 22-genes_47-edges_Dahlquist-data_Sigmoidal_forward_graph.xlsx file downloaded from the Master Branch.  Closing.
